### ISSUE TITLE
Remove clear button on submit existing

### ISSUE THREAD

**Issue by nathankota** [agrc/plss#134] opened 2022-11-07 23:09 UTC
On the first page of the existing monument submission pathway, change the `Clear` button to `Back`. When `Back` is clicked:
- Returns to identify page
- If user selects the existing sheet pathway again, any data they already uploaded or entered remains 
- If user selects the new sheet submission path, any previously-entered data in the existing sheet path is reset/removed/deleted
- (Back button should be same yellow color as other existing back buttons)

![image](https://user-images.githubusercontent.com/15659642/200433600-2e5f4c6d-823f-41a1-bf12-e4f83cdffc2e.png)

**Comment by steveoh** [comment] 2022-11-08 01:43
This seems to be a duplicate of #130

**Comment by nathankota** [comment] 2022-11-08 14:17
> This seems to be a duplicate of #130

I altered the title of #130 slightly to account for the difference between the two. It makes sense on the first page of the new sheet path to have all three buttons (back, clear, next), but for an existing sheet it only makes sense to have back and next because there is no keyed-in data to be cleared, and any uploaded file can be removed via #133.

**Closed** 2022-11-14 17:47 UTC
